text = "У вас есть строка 'Запуск Ethereum 2.0 состоится 1 декабря. На депозитарный контракт внесено более 524 288 ETH'"
a = text.split( ' ')
print(type(a[0]))
print(type(a[1]))
print(type(a[2]))
print(type(a[3]))
print(type(a[4]))
print(type(a[5]))
print(type(a[6]))
print(type(a[7]))
print(type(a[8]))
print(type(a[9]))
print(type(a[10]))
print(type(a[11]))
print(type(a[12]))
print(type(a[13]))
print(type(a[14]))
print(type(a[15]))
print(type(a[16]))
print(type(a[17]))
